# Generated by Django 2.1 on 2018-08-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNapp', '0002_auto_20180815_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='PNapp/img/user.png', upload_to=''),
        ),
    ]
