# Generated by Django 2.1 on 2018-08-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNapp', '0003_auto_20180816_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='PNapp/profpics/user.png', upload_to=''),
        ),
    ]
